version: '3.9'

services:

  mongo_db:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  go_api:
    build: .
    ports:
      - 1323:1323
    environment:
      MONGOURI: mongodb://mongo_db:27017
      EMAIL_SENDER_NAME: abel.wen0@gmail.com
      EMAIL_PASSWORD: nchd kzcp kudn aemx
    depends_on:
        - mongo_db
volumes:
  mongo_db: {}

